### ISSUE TITLE
Converting AnsiString to PAnsiChar with @Str[1] raises ERangeError for empty strings.

### ISSUE THREAD

**Issue by BigAl66** [Possseidon/Pengine#1]
https://github.com/Possseidon/Pengine/blob/0cb62f18ac07d7735793f561c87a1e78d831bd00/Libraries/OpenGL/Pengine.GLProgram.pas#L363

If string is empty you get a ERangeError :-).

**Comment by Possseidon** [comment]
I have range checking turned off and it seems to simply return nil in that case, which is okay. However yes, it is better to simply cast the string using PAnsiChar(AText), which handles an empty string correctly.

**Comment by Possseidon** [comment]
Fixed.
